WebApi/Orchard-1.10.1/src/Orchard.Web/Modules/Orchard.Layouts/Controllers/BlueprintAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Orchard.Caching;
using Orchard.ContentManagement;
using Orchard.Data;
using Orchard.DisplayManagement;
using Orchard.Layouts.Framework.Drivers;
using Orchard.Layouts.Framework.Elements;
using Orchard.Layouts.Helpers;
using Orchard.Layouts.Services;
using Orchard.Layouts.ViewModels;
using Orchard.Localization;
using Orchard.Mvc;
using Orchard.UI.Admin;
using Orchard.UI.Notify;

namespace Orchard.Layouts.Controllers {
    [Admin]
    public class BlueprintAdminController : Controller, IUpdateModel {
        private readonly IElementBlueprintService _elementBlueprintService;
        private readonly INotifier _notifier;
        private readonly IElementManager _elementManager;
        private readonly ICultureAccessor _cultureAccessor;
        private readonly IShapeFactory _shapeFactory;
        private readonly ITransactionManager _transactionManager;
        private readonly ISignals _signals;

        public BlueprintAdminController(
            IElementBlueprintService elementBlueprintService, 
            INotifier notifier, 
            IElementManager elementManager, 
            ICultureAccessor cultureAccessor, 
            IShapeFactory shapeFactory, 
            ITransactionManager transactionManager, 
            ISignals signals,
            IOrchardServices orchardServices) {

            _elementBlueprintService = elementBlueprintService;
            _notifier = notifier;
            _elementManager = elementManager;
            _cultureAccessor = cultureAccessor;
            _shapeFactory = shapeFactory;
            _transactionManager = transactionManager;
            _signals = signals;
            Services = orchardServices;

            T = NullLocalizer.Instance;
        }

        public IOrchardServices Services { get; set; }
        public Localizer T { get; set; }

        public ActionResult Index() {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            var blueprints = _elementBlueprintService.GetBlueprints().ToArray();
            var viewModel = new BlueprintsIndexViewModel {
                Blueprints = blueprints
            };
            return View(viewModel);
        }

        public ActionResult Browse() {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            var categories = RemoveBlueprints(_elementManager.GetCategories(DescribeElementsContext.Empty)).ToArray();
            var viewModel = new BrowseElementsViewModel {
                Categories = categories
            };
            return View(viewModel);
        }

        public ActionResult Create(string id) {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            if (String.IsNullOrWhiteSpace(id))
                return RedirectToAction("Browse");

            var describeContext = DescribeElementsContext.Empty;
            var descriptor = _elementManager.GetElementDescriptorByTypeName(describeContext, id);
            var baseElement = _elementManager.ActivateElement(descriptor);
            var viewModel = new CreateElementBlueprintViewModel {
                BaseElement = baseElement
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(string id, CreateElementBlueprintViewModel model) {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            var describeContext = DescribeElementsContext.Empty;
            var descriptor = _elementManager.GetElementDescriptorByTypeName(describeContext, id);
            var baseElement = _elementManager.ActivateElement(descriptor);

            model.BaseElement = baseElement;

            if (!ModelState.IsValid) {
                return View(model);
            }

            var blueprint = _elementBlueprintService.CreateBlueprint(
                baseElement, 
                model.ElementTypeName.TrimSafe(),
                model.ElementDisplayName.TrimSafe(),
                model.ElementDescription.TrimSafe(),
                model.ElementCategory.TrimSafe());

            return RedirectToAction("Edit", new { id = blueprint.Id });
        }

        public ActionResult Edit(int id) {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            var blueprint = _elementBlueprintService.GetBlueprint(id);
            var describeContext = DescribeElementsContext.Empty;
            var descriptor = _elementManager.GetElementDescriptorByTypeName(describeContext, blueprint.BaseElementTypeName);
            var data = ElementDataHelper.Deserialize(blueprint.BaseElementState);
            var element = _elementManager.ActivateElement(descriptor, e => e.Data = data);
            var context = CreateEditorContext(element, data);
            var editorResult = _elementManager.BuildEditor(context);

            var viewModel = new EditElementBlueprintViewModel {
                EditorResult = editorResult,
                TypeName = blueprint.BaseElementTypeName,
                DisplayText = descriptor.DisplayText,
                Description = descriptor.Description,
                ElementData = element.Data.Serialize(),
                Tabs = editorResult.CollectTabs().ToArray(),
                BaseElement = element
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, ElementDataViewModel model) {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            var blueprint = _elementBlueprintService.GetBlueprint(id);
            var describeContext = DescribeElementsContext.Empty;
            var descriptor = _elementManager.GetElementDescriptorByTypeName(describeContext, blueprint.BaseElementTypeName);
            var data = ElementDataHelper.Deserialize(model.ElementData).Combine(Request.Form.ToDictionary());
            var element = _elementManager.ActivateElement(descriptor, e => e.Data = data);
            var context = CreateEditorContext(element, elementData: data);
            var editorResult = _elementManager.UpdateEditor(context);
            var viewModel = new EditElementBlueprintViewModel {
                EditorResult = editorResult,
                TypeName = model.TypeName,
                DisplayText = descriptor.DisplayText,
                Description = descriptor.Description,
                ElementData = element.Data.Serialize(),
                Tabs = editorResult.CollectTabs().ToArray(),
                BaseElement = element
            };

            if (!ModelState.IsValid) {
                _transactionManager.Cancel();
                return View(viewModel);
            }

            blueprint.BaseElementState = data.Serialize();
            _signals.Trigger(Signals.ElementDescriptors);
            _notifier.Information(T("That blueprint has been saved."));
            return RedirectToAction("Index");
        }

        public ActionResult Properties(int id) {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            var blueprint = _elementBlueprintService.GetBlueprint(id);
            var describeContext = DescribeElementsContext.Empty;
            var descriptor = _elementManager.GetElementDescriptorByTypeName(describeContext, blueprint.BaseElementTypeName);
            var baseElement = _elementManager.ActivateElement(descriptor);
            var viewModel = new ElementBlueprintPropertiesViewModel {
                BaseElement = baseElement,
                ElementDisplayName = blueprint.ElementDisplayName,
                ElementDescription = blueprint.ElementDescription,
                ElementTypeName = blueprint.ElementTypeName,
                ElementCategory = blueprint.ElementCategory
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Properties(int id, ElementBlueprintPropertiesViewModel model) {
            if (!Services.Authorizer.Authorize(Permissions.ManageLayouts, T("Not authorized to manage layouts."))) {
                return new HttpUnauthorizedResult();
            }

            var blueprint = _elementBlueprintService.GetBlueprint(id);
            var describeContext = DescribeElementsContext.Empty;
            var descriptor = _elementManager.GetElementDescriptorByTypeName(describeContext, blueprint.BaseElementTypeName);
            var baseElement = _elementManager.ActivateElement(descriptor);

            model.BaseElement = baseElement;
            model.ElementTypeName = blueprint.ElementTypeName;

            if (!ModelState.IsValid) {
                return View(model);
            }

            blueprint.ElementDisplayName = model.ElementDisplayName.TrimSafe();
            blueprint.ElementDescription = model.ElementDescription.TrimSafe();
            blueprint.ElementCategory = model.ElementCategory.TrimSafe();

            _notifier.Information(T("That blueprint's properties have been saved."));
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id) {

WebApi/Orchard-1.10.1/src/Orchard.Web/Modules/Orchard.Layouts/Views/BlueprintAdmin/Browse.cshtml
@using Orchard.Utility.Extensions
@model Orchard.Layouts.ViewModels.BrowseElementsViewModel
@{
    Style.Include("element-browser.css");
    Script.Require("jQuery");
    Script.Include("element-browser.js");

    // Only display categories that have at least a single (non-system) element.
    var categories = Model.Categories.Where(x => x.Elements.Any(e => !e.IsSystemElement)).ToArray();

    Layout.Title = T("Choose Base Element");
    Layout.LocalNavigation.Add(New.ElementBrowser_Tabs(Categories: categories));
}
<div class="element-browser">
    @foreach (var category in categories) {
        <div id="cat-@category.Name.HtmlClassify()" class="elements">
            <ul>
                @foreach (var element in category.Elements) {
                    if (element.IsSystemElement) {
                        continue;
                    }
                    <li>
                        <a class="element" href="@Url.Action("Create", "BlueprintAdmin", new { id = element.TypeName, area = "Orchard.Layouts" })">
                            <h2>@element.DisplayText</h2>
                        </a>
                    </li>
                }
            </ul>
        </div>
    }
</div>

WebApi/Orchard-1.10.1/src/Orchard.Web/Modules/Orchard.Layouts/Views/BlueprintAdmin/Create.cshtml
@model Orchard.Layouts.ViewModels.CreateElementBlueprintViewModel
@{
    Layout.Title = T("Create Element based on {0}", Model.BaseElement.DisplayText);
}
@using (Html.BeginFormAntiForgeryPost()) {
    @Html.ValidationSummary()
    <fieldset>
        <div>
            @Html.LabelFor(m => m.ElementDisplayName, T("Element Display Name"))
            @Html.TextBoxFor(m => m.ElementDisplayName, new { @class = "text large" })
            @Html.Hint(T("The friendly name of the specialized element. Example: Special {0}.", Model.BaseElement.Descriptor.DisplayText))
        </div>
        <div>
            @Html.LabelFor(m => m.ElementTypeName, T("Element Type Name"))
            @Html.TextBoxFor(m => m.ElementTypeName, new { @class = "text large" })
            @Html.Hint(T("The technical type name of the specialized element. Example: Acme.Elements.Special{0}.", Model.BaseElement.Descriptor.DisplayText))
        </div>
        <div>
            @Html.LabelFor(m => m.ElementDescription, T("Element Description"))
            @Html.TextBoxFor(m => m.ElementDescription, new { @class = "text large" })
            @Html.Hint(T("Optionally enter a description for this element."))
        </div>
        <div>
            @Html.LabelFor(m => m.ElementCategory, T("Element Category"))
            @Html.TextBoxFor(m => m.ElementCategory, new { @class = "text large" })
            @Html.Hint(T("Optionally specify a category for this element."))
        </div>
    </fieldset>
    <button type="submit">@T("Create")</button>
    @Html.ActionLink(T("Cancel").Text, "Browse", new { area = "Orchard.Layouts" }, new { @class = "button" })
}

WebApi/Orchard-1.10.1/src/Orchard.Web/Modules/Orchard.Layouts/Views/BlueprintAdmin/Edit.cshtml
@model Orchard.Layouts.ViewModels.EditElementBlueprintViewModel
@{
    Layout.Title = T("Edit Element based on {0}", Model.BaseElement.DisplayText);
}
@using (Html.BeginFormAntiForgeryPost()) {
    @Html.Partial("ElementBlueprintEditor", Model, ViewData)
    <button type="submit">@T("Save")</button>
    @Html.ActionLink(T("Back").Text, "Index", "BlueprintAdmin", new { area = "Orchard.Layouts" }, new { @class = "button" })
}

WebApi/Orchard-1.10.1/src/Orchard.Web/Modules/Orchard.Layouts/Views/BlueprintAdmin/Index.cshtml
@model Orchard.Layouts.ViewModels.BlueprintsIndexViewModel
@{
    Layout.Title = T("Elements");
}
<div class="manage">
    @Html.ActionLink(T("Create").Text, "Create", "BlueprintAdmin", new { area = "Orchard.Layouts" }, new { @class = "button primaryAction" })
</div>
@using (Html.BeginFormAntiForgeryPost()) {
    <fieldset class="bulk-actions">
        <label for="publishActions">@T("Actions:")</label>
        <select id="publishActions" name="Options.BulkAction">
            @Html.SelectOption("", false, T("Choose action...").ToString())
            @Html.SelectOption("Delete", false, T("Delete").ToString())
        </select>
        <button type="submit" name="submit.BulkEdit" value="yes">@T("Apply")</button>
    </fieldset>
    <table class="items">
        <thead>
            <tr>
                <th><input type="checkbox" class="check-all" /></th>
                <th>@T("Display Name")</th>
                <th>@T("Name")</th>
                <th>@T("Base Element")</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var blueprint in Model.Blueprints) {
                <tr>
                    <td><input type="checkbox" value="@blueprint.Id" name="blueprintIds" /></td>
                    <td>@blueprint.ElementDisplayName</td>
                    <td>@blueprint.ElementTypeName</td>
                    <td>@blueprint.BaseElementTypeName</td>
                    <td>
                        @Html.ActionLink(T("Edit").Text, "Edit", "BlueprintAdmin", new { id = blueprint.Id, area = "Orchard.Layouts" }, null) @T(" | ")
                        @Html.ActionLink(T("Properties").Text, "Properties", "BlueprintAdmin", new { id = blueprint.Id, area = "Orchard.Layouts" }, null) @T(" | ")
                        @Html.ActionLink(T("Remove").Text, "Delete", "BlueprintAdmin", new { id = blueprint.Id, area = "Orchard.Layouts" }, new { itemprop = "RemoveUrl UnsafeUrl" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

WebApi/Orchard-1.10.1/src/Orchard.Web/Modules/Orchard.Layouts/Views/BlueprintAdmin/Properties.cshtml
@model Orchard.Layouts.ViewModels.ElementBlueprintPropertiesViewModel
@{
    Layout.Title = T("Edit Element Properties based on {0}", Model.BaseElement.DisplayText);
}
@using (Html.BeginFormAntiForgeryPost()) {
    @Html.ValidationSummary()
    <fieldset>
        <div>
            @Html.LabelFor(m => m.ElementDisplayName, T("Element Display Name"))
            @Html.TextBoxFor(m => m.ElementDisplayName, new { @class = "text large" })
            @Html.Hint(T("The friendly name of the specialized element. Example: Special {0}", Model.BaseElement.Descriptor.DisplayText))
        </div>
        <div>
            @Html.LabelFor(m => m.ElementTypeName, T("Element Type Name"))
            @Html.TextBoxFor(m => m.ElementTypeName, new { @class = "text large disabled", disabled = "disabled" })
            @Html.Hint(T("The technical type name of the specialized element. Example: Acme.Elements.Special{0}", Model.BaseElement.Descriptor.DisplayText))
        </div>
        <div>
            @Html.LabelFor(m => m.ElementDescription, T("Element Description"))
            @Html.TextBoxFor(m => m.ElementDescription, new { @class = "text large" })
            @Html.Hint(T("Optionally enter a description for this element."))
        </div>
        <div>
            @Html.LabelFor(m => m.ElementCategory, T("Element Category"))
            @Html.TextBoxFor(m => m.ElementCategory, new { @class = "text large" })
            @Html.Hint(T("Optionally specify a category for this element."))
        </div>
    </fieldset>
    <button type="submit">@T("Save")</button>
    @Html.ActionLink(T("Cancel").Text, "Index", new { area = "Orchard.Layouts" }, new { @class = "button" })
}